import COLORS from "@/constants/colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  employeeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.white,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.gray_100,
    shadowColor: COLORS.brand_950,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  employeeCardGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.brand_50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
  },
  initials: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    color: COLORS.brand_950,
  },
  employeeInfo: {
    flex: 1,
    gap: 2,
  },
  employeeName: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    color: COLORS.gray_900,
  },
  employeeRole: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    color: COLORS.brand_700,
  },
  checkTime: {
    fontFamily: 'Inter_400Regular',
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 16,
    color: COLORS.gray_500,
  },
  time: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
    color: COLORS.gray_700,
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
  },
  cancelButton: {
    backgroundColor: COLORS.error_50,
  },
  confirmButton: {
    backgroundColor: COLORS.brand_50,
  },
  infoButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 4,
  },
  infoText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  rejectButton: {
    backgroundColor: COLORS.error_50,
  },
  acceptButton: {
    backgroundColor: COLORS.brand_50,
  },
  rejectText: {
    color: COLORS.error_700,
  },
  acceptText: {
    color: COLORS.brand_950,
  },
  modalGroup: {
    width: '100%',
    flex: 1,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray_100,
  },
  modalGroupButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  textArea: {
    width: '100%',
    minHeight: 100,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.gray_200,
    padding: 14,
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    color: COLORS.gray_900,
    textAlignVertical: 'top',
  },
  rejectModal: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 28,
    marginBottom: 24,
    textAlign: 'center',
    color: COLORS.gray_900,
  },
  title: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    color: COLORS.gray_900,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderColor: COLORS.gray_100,
    borderWidth: 1,
    padding: 14,
    gap: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  selectedItem: {
    backgroundColor: COLORS.brand_25,
    borderColor: COLORS.brand_950,
  },
});

export default styles;
